#!/usr/bin/env bash
# script that displays Best School 10 times, 9th iteration, displays Best School and Hi on a new line.

COUNTER=0
while [ $COUNTER -lt 11 ]
do
    if [ $COUNTER = 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((COUNTER+=1))
done
